#pragma once
// NT FUNCTIONS DOCS: http://undocumented.ntinternals.net/index.html
#include <winternl.h>

NTSTATUS(NTAPI* NtQueryDirectoryObject)(HANDLE, PVOID, ULONG, BOOLEAN, BOOLEAN, PULONG, PULONG);
NTSTATUS(NTAPI* NtQuerySymbolicLinkObject)(HANDLE, PUNICODE_STRING, PULONG);
NTSTATUS(NTAPI* NtQueryMutant)(HANDLE, MUTANT_INFORMATION_CLASS, PVOID, ULONG, PULONG);
NTSTATUS(NTAPI* NtQuerySection)(HANDLE, SECTION_INFORMATION_CLASS, PVOID, ULONG, PULONG);
NTSTATUS(NTAPI* NtQueryEvent)(HANDLE, EVENT_INFORMATION_CLASS, PVOID, ULONG, PULONG);
NTSTATUS(NTAPI* NtQuerySemaphore)(HANDLE, SEMAPHORE_INFORMATION_CLASS, PVOID, ULONG, PULONG);
NTSTATUS(NTAPI* NtQueryTimer)(HANDLE, TIMER_INFORMATION_CLASS, PVOID, ULONG, PULONG);

//NTSTATUS(NTAPI* NtQueryObject)(HANDLE, OBJECT_INFORMATION_CLASS, PVOID, ULONG, PULONG);
NTSTATUS(NTAPI* NtOpenDirectoryObject)(PHANDLE, ACCESS_MASK, POBJECT_ATTRIBUTES);
NTSTATUS(NTAPI* NtOpenSymbolicLinkObject)(PHANDLE, ACCESS_MASK, POBJECT_ATTRIBUTES);
NTSTATUS(NTAPI* NtOpenMutant)(PHANDLE, ACCESS_MASK, POBJECT_ATTRIBUTES);
NTSTATUS(NTAPI* NtOpenSection)(PHANDLE, ACCESS_MASK, POBJECT_ATTRIBUTES);
NTSTATUS(NTAPI* NtOpenEvent)(PHANDLE, ACCESS_MASK, POBJECT_ATTRIBUTES);
NTSTATUS(NTAPI* NtOpenSemaphore)(PHANDLE, ACCESS_MASK, POBJECT_ATTRIBUTES);
NTSTATUS(NTAPI* NtOpenTimer)(PHANDLE, ACCESS_MASK, POBJECT_ATTRIBUTES);
//NTSTATUS(NTAPI* NtOpenKey)(PHANDLE, ACCESS_MASK, POBJECT_ATTRIBUTES);
//NTSTATUS(NTAPI* NtOpenEventPair)(PHANDLE, ACCESS_MASK, POBJECT_ATTRIBUTES);
//NTSTATUS(NTAPI* NtOpenIoCompletion)(PHANDLE, ACCESS_MASK, POBJECT_ATTRIBUTES);
//NtOpenFile still works

VOID(NTAPI* RtlInitUnicodeString_)(PUNICODE_STRING, PCWSTR);
NTSTATUS(NTAPI* NtClose_)(HANDLE);
